ARG PHP_EXTENSIONS="mysqli pgsql pdo_mysql pdo_pgsql"

FROM thecodingmachine/php:8.3-v4-apache-node18
WORKDIR /workspace
# RUN bash /workspace/.devcontainer/setup.sh
# CMD ["sh", "/workspace/.devcontainer/setup.sh"]