version: "3"
services:
  app:
    build: ./docker/app
    volumes:
      - ../:/workspace:cached
    ports:
      - 80:80
    tty: true
    environment:
        APP_ENV: local
        PHP_EXTENSION_XDEBUG: 1
        PHP_EXTENSION_PGSQL: 1
        PHP_EXTENSION_PDO_PGSQL: 1
        APACHE_DOCUMENT_ROOT: /workspace/public
  database:
    image: 'mariadb:10'
    environment:
        MYSQL_ROOT_PASSWORD: 'password'
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: 'sura'
        MYSQL_USER: 'sura'
        MYSQL_PASSWORD: 'password'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
        - 'database:/var/lib/mysql'
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-ppassword"]
        retries: 3
        timeout: 5s
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025