version: "3"
services:
  app:
    build: ./docker/app
    volumes:
      - ../:/workspace:cached
    ports:
      - 5183:5183
    tty: true
    environment:
        APP_ENV: local
        PHP_EXTENSION_XDEBUG: 1
        PHP_EXTENSION_GD: 1
        PHP_EXTENSION_PGSQL: 1
        PHP_EXTENSION_PDO_PGSQL: 1
        APACHE_DOCUMENT_ROOT: /workspace/public
  db:
    image: mariadb
    restart: always
    ports:
        - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD: example
      MYSQL_USER: mariadb
      MYSQL_DATABASE: mariadb
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080        
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379